services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
    environment:
      POSTGRES_PASSWORD: "password"
  web:
    build: .
    volumes:
      - .:/usr/src/intern-egift-system
      - bundle:/usr/local/bundle
    ports:
      - "80:3000"
    environment:
      RAILS_ENV: "development"
      DATABASE_HOST: "db"
      DATABASE_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    depends_on:
      - db

volumes:
  postgres-data:
  bundle:
