services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/intern-egift-system
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development

volumes:
  bundle:
