services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "egift_system_development"

  web:
    build: .
    volumes:
      - .:/usr/src/intern-egift-system
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: "development"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "egift_system_development"
      DATABASE_HOST: "db"
      DATABASE_USER: "postgres"
    depends_on:
      - db

volumes:
  postgres-data:
  bundle:
